### ISSUE TITLE
Handling bad credentials

### ISSUE THREAD

**Issue by michpetrov** [jboss-set/aphrodite#170]
Kinda related to #143 

When initializing Aphrodite with bad credentials, only BZ tracker will outright fail. JIRA tracker is created and just does nothing (an exception is thrown due to an empty string after a request). Likewise GitHub repository service is created but at least it logs a message with "bad credentials" after a request. IMHO in case of bad credentials Aphrodite should fail to initialize.

**Comment by baranowb** [comment]
Repository service cant handle this, since you supply creds for all bunch of repos and fetch different stuff - depending on what you fetch/want do, creds might be enough or not.

In case of JIRA: "Actually JIRA doesn't have this kind of API to check the username/password validity. "
BZ fail due internal implementation, JIRA does not have this, though I might be able to figure a workaround.
